[
  "com.google.Chrome"
  "com.usebottles.bottles"
  # "com.discordapp.Discord"
  "im.riot.Riot" # Element
  "org.mozilla.firefox"
  "it.mijorus.gearlever"
  "org.gimp.GIMP"
  "io.github.milkshiift.GoofCord"
  "com.google.EarthPro"
  "org.libreoffice.LibreOffice"
  #"net.lutris.Lutris"
  "net.mediaarea.MediaInfo"
  "com.nextcloud.desktopclient.nextcloud"
  "com.vysp3r.ProtonPlus"
  "com.github.Matoking.protontricks"
  "io.github.Qalculate.qalculate-qt"
  "org.quassel_irc.QuasselClient"
  "com.github.ryonakano.reco" # Audio recorder
  "org.remmina.Remmina"
  "org.torproject.torbrowser-launcher"
  "dev.vencord.Vesktop"
  "com.rtosta.zapzap"
  "us.zoom.Zoom"
]
